/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package aplications;

import dao.AluguelDao;
import dao.LivroDao;
import java.awt.Image;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import models.Aluguel;
import models.Livro;
import models.Usuario;

/**
 *
 * @author Penna
 */
public class FramePesquisarLivros extends javax.swing.JFrame {

    private static Usuario usuario;

    public FramePesquisarLivros(Usuario usuario) {
        this.usuario = usuario;
        initComponents();
        listarTabela();
        redimensionarImagem();
    }
    
     private void redimensionarImagem() {
        // Carregar a imagem original
        ImageIcon icon = new ImageIcon(getClass().getResource("/imagens/1722.jpg"));
        
        // Redimensionar a imagem para caber no JPanel (jPanel2)
        Image img = icon.getImage().getScaledInstance(jPanel1.getWidth(), jPanel1.getHeight(), Image.SCALE_SMOOTH);
        
        // Definir a imagem redimensionada no JLabel
        jLabelImagem.setIcon(new ImageIcon(img));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableLivros = new javax.swing.JTable();
        jBtnAlugar = new javax.swing.JButton();
        jBtnVoltar = new javax.swing.JButton();
        jLabelImagem = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTableLivros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Titulo", "Autor", "Genero", "Disponiveis"
            }
        ));
        jScrollPane1.setViewportView(jTableLivros);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 299, 747, 180));

        jBtnAlugar.setText("ALUGAR");
        jBtnAlugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAlugarActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnAlugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 230, 177, 45));

        jBtnVoltar.setText("VOLTAR");
        jBtnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnVoltarActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(532, 230, 215, 45));
        jPanel1.add(jLabelImagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnAlugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAlugarActionPerformed
        int setar = jTableLivros.getSelectedRow();
        if (setar != -1) {
            String qtdString = jTableLivros.getModel().getValueAt(setar, 4).toString();
            int qtdInt = Integer.parseInt(qtdString);

        if (qtdInt > 0) {
            String idLivroString = jTableLivros.getModel().getValueAt(setar, 0).toString();
            int idLivroInt = Integer.parseInt(idLivroString);

            Aluguel aluguel = new Aluguel(usuario.getId(), idLivroInt);
            AluguelDao aluguelDao = new AluguelDao();

            // Verifica se o usuário já alugou o livro
            boolean jaAlugado = aluguelDao.verificarAluguelExistente(usuario.getId(), idLivroInt);

            if (!jaAlugado) {
                aluguelDao.inserirAluguel(aluguel);
                aluguelDao.atualizarAluguelDisponiveisDecrementar(aluguel); // Atualiza a disponibilidade do livro
                
                limparTabela(); // Limpa a tabela antes de listar novamente
                listarTabela(); // Lista os livros atualizados

                JOptionPane.showMessageDialog(null, "Alugado com sucesso!", "AVISO", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(null, "Este livro já foi alugado por você!", "AVISO", JOptionPane.WARNING_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Este livro está indisponível no momento!", "AVISO", JOptionPane.INFORMATION_MESSAGE);
        }
    } else {
        JOptionPane.showMessageDialog(null, "Selecione um livro!", "ERRO", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_jBtnAlugarActionPerformed

    private void jBtnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnVoltarActionPerformed
        FrameMenuBiblioteca f = new FrameMenuBiblioteca(usuario);
        f.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_jBtnVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public void listarTabela() {
        LivroDao livro = new LivroDao();
        ArrayList<Livro> listarLivros = livro.listarLivros();
        DefaultTableModel dtm = (DefaultTableModel) jTableLivros.getModel();

        jTableLivros.getColumnModel().getColumn(0).setPreferredWidth(50);
        jTableLivros.getColumnModel().getColumn(1).setPreferredWidth(230);
        jTableLivros.getColumnModel().getColumn(2).setPreferredWidth(150);
        jTableLivros.getColumnModel().getColumn(3).setPreferredWidth(100);
        jTableLivros.getColumnModel().getColumn(4).setPreferredWidth(50);

        for (Livro livros : listarLivros) {
            Object[] ob = {livros.getId(), livros.getTitulo(), livros.getAutor(), livros.getGenero(), livros.getQuantidadeDisponivel()};
            dtm.addRow(ob);
        }
    }

    public void limparTabela() {
        DefaultTableModel dtm = (DefaultTableModel) jTableLivros.getModel();
        dtm.setRowCount(0); // Remove todas as linhas da tabela
    }

    public void alugarLivro() {

        int setar = jTableLivros.getSelectedRow();
        String idLivroString = jTableLivros.getModel().getValueAt(setar, 0).toString();
        int idLivro = Integer.parseInt(idLivroString);
        //colocar na tabela aluguel se tiver livros disponiveis
        Aluguel aluguel = new Aluguel(usuario.getId(), idLivro);
        AluguelDao aluguelDao = new AluguelDao();
        aluguelDao.inserirAluguel(aluguel);

    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FramePesquisarLivros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FramePesquisarLivros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FramePesquisarLivros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FramePesquisarLivros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FramePesquisarLivros(usuario).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAlugar;
    private javax.swing.JButton jBtnVoltar;
    private javax.swing.JLabel jLabelImagem;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableLivros;
    // End of variables declaration//GEN-END:variables
}
